_BASE_: "Base-RCNN.yaml"
MODEL:
  WEIGHTS: "data/.pretrain_weights/ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
  ROI_HEADS:
    NUM_CLASSES: 101
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
DATASETS:
  TRAIN: ('vizwiz_train',)
  TEST: ('vizwiz_val',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (85000, 100000)
  MAX_ITER: 110000
  CHECKPOINT_PERIOD: 200000
OUTPUT_DIR: "output/vizwiz_base"
