_BASE_: "Base-RCNN.yaml"
MODEL:
  WEIGHTS: ""
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "Res5ROIHeads"
    NUM_CLASSES: 101
    SCORE_THRESH_TEST: 0.05
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('vizwiz_train',)
  TEST: ('vizwiz_val',)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  WEIGHT_DECAY_NORM: 0.0
  STEPS: (2083, 2777)
  MAX_ITER: 3472
  WARMUP_ITERS: 500
  WARMUP_FACTOR: 0.001
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "./outputs/vizwiz_base"

